/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.ZustandsdiagrammRuntimeModule;
import org.xtext.example.mydsl.ZustandsdiagrammStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ZustandsdiagrammIdeSetup extends ZustandsdiagrammStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ZustandsdiagrammRuntimeModule(), new ZustandsdiagrammIdeModule()));
	}
	
}
