/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.example.mydsl.tests.ZustandsdiagrammInjectorProvider;
import org.xtext.example.mydsl.zustandsdiagramm.Model;

@ExtendWith(InjectionExtension.class)
@InjectWith(ZustandsdiagrammInjectorProvider.class)
@SuppressWarnings("all")
public class ZustandsdiagrammParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("initialState: aus with event: stromEin to gruen;\t\t");
      _builder.newLine();
      _builder.append("genericState: gruen with event: timerAblauf to gelb;");
      _builder.newLine();
      _builder.append("genericState: gelb with event: timerAblauf to rot;");
      _builder.newLine();
      _builder.append("genericState: rot with event: timerAblauf and guard: keineAmpelGruen to rotGelb;\t");
      _builder.newLine();
      _builder.append("genericState: rotGelb with event: timerAblauf to gruen;\t");
      _builder.newLine();
      _builder.append("finalState: aus;\t");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
