/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.zustandsdiagramm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generic State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.zustandsdiagramm.GenericState#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.zustandsdiagramm.GenericState#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getGenericState()
 * @model
 * @generated
 */
public interface GenericState extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(TargetableState)
   * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getGenericState_Name()
   * @model containment="true"
   * @generated
   */
  TargetableState getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.zustandsdiagramm.GenericState#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(TargetableState value);

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.zustandsdiagramm.Transition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getGenericState_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

} // GenericState
