/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.zustandsdiagramm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initial State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.zustandsdiagramm.InitialState#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.zustandsdiagramm.InitialState#getTransition <em>Transition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getInitialState()
 * @model
 * @generated
 */
public interface InitialState extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getInitialState_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.zustandsdiagramm.InitialState#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition</em>' containment reference.
   * @see #setTransition(Transition)
   * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getInitialState_Transition()
   * @model containment="true"
   * @generated
   */
  Transition getTransition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.zustandsdiagramm.InitialState#getTransition <em>Transition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transition</em>' containment reference.
   * @see #getTransition()
   * @generated
   */
  void setTransition(Transition value);

} // InitialState
