/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.zustandsdiagramm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.zustandsdiagramm.Model#getInitialState <em>Initial State</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.zustandsdiagramm.Model#getFinalState <em>Final State</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.zustandsdiagramm.Model#getGenericState <em>Generic State</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Initial State</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.zustandsdiagramm.InitialState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial State</em>' containment reference list.
   * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getModel_InitialState()
   * @model containment="true"
   * @generated
   */
  EList<InitialState> getInitialState();

  /**
   * Returns the value of the '<em><b>Final State</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.zustandsdiagramm.FinalState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Final State</em>' containment reference list.
   * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getModel_FinalState()
   * @model containment="true"
   * @generated
   */
  EList<FinalState> getFinalState();

  /**
   * Returns the value of the '<em><b>Generic State</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.zustandsdiagramm.GenericState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic State</em>' containment reference list.
   * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammPackage#getModel_GenericState()
   * @model containment="true"
   * @generated
   */
  EList<GenericState> getGenericState();

} // Model
