/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.zustandsdiagramm;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.zustandsdiagramm.ZustandsdiagrammFactory
 * @model kind="package"
 * @generated
 */
public interface ZustandsdiagrammPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "zustandsdiagramm";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Zustandsdiagramm";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "zustandsdiagramm";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ZustandsdiagrammPackage eINSTANCE = org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ModelImpl
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Initial State</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__INITIAL_STATE = 0;

  /**
   * The feature id for the '<em><b>Final State</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FINAL_STATE = 1;

  /**
   * The feature id for the '<em><b>Generic State</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GENERIC_STATE = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.TargetableStateImpl <em>Targetable State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.TargetableStateImpl
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getTargetableState()
   * @generated
   */
  int TARGETABLE_STATE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGETABLE_STATE__NAME = 0;

  /**
   * The number of structural features of the '<em>Targetable State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGETABLE_STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.InitialStateImpl <em>Initial State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.InitialStateImpl
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getInitialState()
   * @generated
   */
  int INITIAL_STATE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE__TRANSITION = 1;

  /**
   * The number of structural features of the '<em>Initial State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.FinalStateImpl <em>Final State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.FinalStateImpl
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getFinalState()
   * @generated
   */
  int FINAL_STATE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_STATE__NAME = 0;

  /**
   * The number of structural features of the '<em>Final State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.GenericStateImpl <em>Generic State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.GenericStateImpl
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getGenericState()
   * @generated
   */
  int GENERIC_STATE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERIC_STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERIC_STATE__TRANSITIONS = 1;

  /**
   * The number of structural features of the '<em>Generic State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERIC_STATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.TransitionImpl
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 5;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__EVENT = 0;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TO = 1;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.EventImpl
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__GUARD = 1;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.GuardImpl <em>Guard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.GuardImpl
   * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getGuard()
   * @generated
   */
  int GUARD = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUARD__NAME = 0;

  /**
   * The number of structural features of the '<em>Guard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUARD_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.zustandsdiagramm.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.zustandsdiagramm.Model#getInitialState <em>Initial State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Initial State</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Model#getInitialState()
   * @see #getModel()
   * @generated
   */
  EReference getModel_InitialState();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.zustandsdiagramm.Model#getFinalState <em>Final State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Final State</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Model#getFinalState()
   * @see #getModel()
   * @generated
   */
  EReference getModel_FinalState();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.zustandsdiagramm.Model#getGenericState <em>Generic State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Generic State</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Model#getGenericState()
   * @see #getModel()
   * @generated
   */
  EReference getModel_GenericState();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.zustandsdiagramm.TargetableState <em>Targetable State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Targetable State</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.TargetableState
   * @generated
   */
  EClass getTargetableState();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.zustandsdiagramm.TargetableState#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.TargetableState#getName()
   * @see #getTargetableState()
   * @generated
   */
  EAttribute getTargetableState_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.zustandsdiagramm.InitialState <em>Initial State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial State</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.InitialState
   * @generated
   */
  EClass getInitialState();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.zustandsdiagramm.InitialState#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.InitialState#getName()
   * @see #getInitialState()
   * @generated
   */
  EAttribute getInitialState_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.zustandsdiagramm.InitialState#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.InitialState#getTransition()
   * @see #getInitialState()
   * @generated
   */
  EReference getInitialState_Transition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.zustandsdiagramm.FinalState <em>Final State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Final State</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.FinalState
   * @generated
   */
  EClass getFinalState();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.zustandsdiagramm.FinalState#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.FinalState#getName()
   * @see #getFinalState()
   * @generated
   */
  EReference getFinalState_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.zustandsdiagramm.GenericState <em>Generic State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Generic State</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.GenericState
   * @generated
   */
  EClass getGenericState();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.zustandsdiagramm.GenericState#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.GenericState#getName()
   * @see #getGenericState()
   * @generated
   */
  EReference getGenericState_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.zustandsdiagramm.GenericState#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.GenericState#getTransitions()
   * @see #getGenericState()
   * @generated
   */
  EReference getGenericState_Transitions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.zustandsdiagramm.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.zustandsdiagramm.Transition#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Transition#getEvent()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Event();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.zustandsdiagramm.Transition#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Transition#getTo()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_To();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.zustandsdiagramm.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.zustandsdiagramm.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.zustandsdiagramm.Event#getGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guard</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Event#getGuard()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Guard();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.zustandsdiagramm.Guard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Guard</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Guard
   * @generated
   */
  EClass getGuard();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.zustandsdiagramm.Guard#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.zustandsdiagramm.Guard#getName()
   * @see #getGuard()
   * @generated
   */
  EAttribute getGuard_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ZustandsdiagrammFactory getZustandsdiagrammFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ModelImpl
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Initial State</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__INITIAL_STATE = eINSTANCE.getModel_InitialState();

    /**
     * The meta object literal for the '<em><b>Final State</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FINAL_STATE = eINSTANCE.getModel_FinalState();

    /**
     * The meta object literal for the '<em><b>Generic State</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GENERIC_STATE = eINSTANCE.getModel_GenericState();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.TargetableStateImpl <em>Targetable State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.TargetableStateImpl
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getTargetableState()
     * @generated
     */
    EClass TARGETABLE_STATE = eINSTANCE.getTargetableState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TARGETABLE_STATE__NAME = eINSTANCE.getTargetableState_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.InitialStateImpl <em>Initial State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.InitialStateImpl
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getInitialState()
     * @generated
     */
    EClass INITIAL_STATE = eINSTANCE.getInitialState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIAL_STATE__NAME = eINSTANCE.getInitialState_Name();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_STATE__TRANSITION = eINSTANCE.getInitialState_Transition();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.FinalStateImpl <em>Final State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.FinalStateImpl
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getFinalState()
     * @generated
     */
    EClass FINAL_STATE = eINSTANCE.getFinalState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FINAL_STATE__NAME = eINSTANCE.getFinalState_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.GenericStateImpl <em>Generic State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.GenericStateImpl
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getGenericState()
     * @generated
     */
    EClass GENERIC_STATE = eINSTANCE.getGenericState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERIC_STATE__NAME = eINSTANCE.getGenericState_Name();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERIC_STATE__TRANSITIONS = eINSTANCE.getGenericState_Transitions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.TransitionImpl
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__EVENT = eINSTANCE.getTransition_Event();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TO = eINSTANCE.getTransition_To();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.EventImpl
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__GUARD = eINSTANCE.getEvent_Guard();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.zustandsdiagramm.impl.GuardImpl <em>Guard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.GuardImpl
     * @see org.xtext.example.mydsl.zustandsdiagramm.impl.ZustandsdiagrammPackageImpl#getGuard()
     * @generated
     */
    EClass GUARD = eINSTANCE.getGuard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUARD__NAME = eINSTANCE.getGuard_Name();

  }

} //ZustandsdiagrammPackage
