/*
 * generated by Xtext 2.21.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import selfie.ui.internal.SelfieActivator;

public class SelfieUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SelfieActivator.getInstance().getInjector("org.xtext.Selfie");
	}

}
