<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modellgetriebeneAufgabe4" nsURI="http://www.example.org/modellgetriebeneAufgabe4"
    nsPrefix="modellgetriebeneAufgabe4">
  <eClassifiers xsi:type="ecore:EClass" name="Selfie">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueable" lowerBound="1"
        eType="#//Valueable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Valueable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//Valueable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntValue" eSuperTypes="#//ValType #//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Types"
        changeable="false" defaultValueLiteral="int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Valueable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleValue" eSuperTypes="#//ValType #//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Types"
        changeable="false" defaultValueLiteral="double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Types">
    <eLiterals name="undef"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="double" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValType" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Valueable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Calculation" eSuperTypes="#//Valueable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftvalue" lowerBound="1"
        eType="#//Valueable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightvalue" lowerBound="1"
        eType="#//Valueable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//Operator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="undef"/>
    <eLiterals name="plus" value="1"/>
    <eLiterals name="minus" value="2"/>
    <eLiterals name="times" value="3"/>
    <eLiterals name="divided" value="4"/>
  </eClassifiers>
</ecore:EPackage>
