/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalZustandsdiagrammParser;
import org.xtext.example.mydsl.services.ZustandsdiagrammGrammarAccess;

public class ZustandsdiagrammParser extends AbstractAntlrParser {

	@Inject
	private ZustandsdiagrammGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalZustandsdiagrammParser createParser(XtextTokenStream stream) {
		return new InternalZustandsdiagrammParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ZustandsdiagrammGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ZustandsdiagrammGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
