/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.Zustandsdiagramm.ui.internal.ZustandsdiagrammActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ZustandsdiagrammExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ZustandsdiagrammActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ZustandsdiagrammActivator activator = ZustandsdiagrammActivator.getInstance();
		return activator != null ? activator.getInjector(ZustandsdiagrammActivator.ORG_XTEXT_EXAMPLE_MYDSL_ZUSTANDSDIAGRAMM) : null;
	}

}
