/**
 * generated by Xtext 2.21.0
 */
package org.xtext.selfie.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.selfie.Assignment;
import org.xtext.selfie.SelfiePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AssignmentImpl extends ExpressionImpl implements Assignment
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AssignmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SelfiePackage.Literals.ASSIGNMENT;
  }

} //AssignmentImpl
