/**
 * generated by Xtext 2.21.0
 */
package org.xtext.selfie.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.selfie.Assignment;
import org.xtext.selfie.SelfiePackage;
import org.xtext.selfie.Valuable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Assignment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selfie.impl.AssignmentImpl#getValuable <em>Valuable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AssignmentImpl extends ExpressionImpl implements Assignment
{
  /**
   * The cached value of the '{@link #getValuable() <em>Valuable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValuable()
   * @generated
   * @ordered
   */
  protected Valuable valuable;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AssignmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SelfiePackage.Literals.ASSIGNMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Valuable getValuable()
  {
    return valuable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValuable(Valuable newValuable, NotificationChain msgs)
  {
    Valuable oldValuable = valuable;
    valuable = newValuable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SelfiePackage.ASSIGNMENT__VALUABLE, oldValuable, newValuable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValuable(Valuable newValuable)
  {
    if (newValuable != valuable)
    {
      NotificationChain msgs = null;
      if (valuable != null)
        msgs = ((InternalEObject)valuable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SelfiePackage.ASSIGNMENT__VALUABLE, null, msgs);
      if (newValuable != null)
        msgs = ((InternalEObject)newValuable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SelfiePackage.ASSIGNMENT__VALUABLE, null, msgs);
      msgs = basicSetValuable(newValuable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelfiePackage.ASSIGNMENT__VALUABLE, newValuable, newValuable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SelfiePackage.ASSIGNMENT__VALUABLE:
        return basicSetValuable(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SelfiePackage.ASSIGNMENT__VALUABLE:
        return getValuable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SelfiePackage.ASSIGNMENT__VALUABLE:
        setValuable((Valuable)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SelfiePackage.ASSIGNMENT__VALUABLE:
        setValuable((Valuable)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SelfiePackage.ASSIGNMENT__VALUABLE:
        return valuable != null;
    }
    return super.eIsSet(featureID);
  }

} //AssignmentImpl
