/**
 * generated by Xtext 2.21.0
 */
package org.xtext.selfie.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.selfie.Operator;
import org.xtext.selfie.SelfiePackage;
import org.xtext.selfie.Valuable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Valuable</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selfie.impl.ValuableImpl#getLeftValue <em>Left Value</em>}</li>
 *   <li>{@link org.xtext.selfie.impl.ValuableImpl#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.selfie.impl.ValuableImpl#getRightValue <em>Right Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ValuableImpl extends MinimalEObjectImpl.Container implements Valuable
{
  /**
   * The cached value of the '{@link #getLeftValue() <em>Left Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftValue()
   * @generated
   * @ordered
   */
  protected Valuable leftValue;

  /**
   * The default value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected static final Operator OPERATOR_EDEFAULT = Operator.PLUS;

  /**
   * The cached value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected Operator operator = OPERATOR_EDEFAULT;

  /**
   * The cached value of the '{@link #getRightValue() <em>Right Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRightValue()
   * @generated
   * @ordered
   */
  protected Valuable rightValue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValuableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SelfiePackage.Literals.VALUABLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Valuable getLeftValue()
  {
    return leftValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLeftValue(Valuable newLeftValue, NotificationChain msgs)
  {
    Valuable oldLeftValue = leftValue;
    leftValue = newLeftValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SelfiePackage.VALUABLE__LEFT_VALUE, oldLeftValue, newLeftValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLeftValue(Valuable newLeftValue)
  {
    if (newLeftValue != leftValue)
    {
      NotificationChain msgs = null;
      if (leftValue != null)
        msgs = ((InternalEObject)leftValue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SelfiePackage.VALUABLE__LEFT_VALUE, null, msgs);
      if (newLeftValue != null)
        msgs = ((InternalEObject)newLeftValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SelfiePackage.VALUABLE__LEFT_VALUE, null, msgs);
      msgs = basicSetLeftValue(newLeftValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelfiePackage.VALUABLE__LEFT_VALUE, newLeftValue, newLeftValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operator getOperator()
  {
    return operator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperator(Operator newOperator)
  {
    Operator oldOperator = operator;
    operator = newOperator == null ? OPERATOR_EDEFAULT : newOperator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelfiePackage.VALUABLE__OPERATOR, oldOperator, operator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Valuable getRightValue()
  {
    return rightValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRightValue(Valuable newRightValue, NotificationChain msgs)
  {
    Valuable oldRightValue = rightValue;
    rightValue = newRightValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SelfiePackage.VALUABLE__RIGHT_VALUE, oldRightValue, newRightValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRightValue(Valuable newRightValue)
  {
    if (newRightValue != rightValue)
    {
      NotificationChain msgs = null;
      if (rightValue != null)
        msgs = ((InternalEObject)rightValue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SelfiePackage.VALUABLE__RIGHT_VALUE, null, msgs);
      if (newRightValue != null)
        msgs = ((InternalEObject)newRightValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SelfiePackage.VALUABLE__RIGHT_VALUE, null, msgs);
      msgs = basicSetRightValue(newRightValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelfiePackage.VALUABLE__RIGHT_VALUE, newRightValue, newRightValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SelfiePackage.VALUABLE__LEFT_VALUE:
        return basicSetLeftValue(null, msgs);
      case SelfiePackage.VALUABLE__RIGHT_VALUE:
        return basicSetRightValue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SelfiePackage.VALUABLE__LEFT_VALUE:
        return getLeftValue();
      case SelfiePackage.VALUABLE__OPERATOR:
        return getOperator();
      case SelfiePackage.VALUABLE__RIGHT_VALUE:
        return getRightValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SelfiePackage.VALUABLE__LEFT_VALUE:
        setLeftValue((Valuable)newValue);
        return;
      case SelfiePackage.VALUABLE__OPERATOR:
        setOperator((Operator)newValue);
        return;
      case SelfiePackage.VALUABLE__RIGHT_VALUE:
        setRightValue((Valuable)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SelfiePackage.VALUABLE__LEFT_VALUE:
        setLeftValue((Valuable)null);
        return;
      case SelfiePackage.VALUABLE__OPERATOR:
        setOperator(OPERATOR_EDEFAULT);
        return;
      case SelfiePackage.VALUABLE__RIGHT_VALUE:
        setRightValue((Valuable)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SelfiePackage.VALUABLE__LEFT_VALUE:
        return leftValue != null;
      case SelfiePackage.VALUABLE__OPERATOR:
        return operator != OPERATOR_EDEFAULT;
      case SelfiePackage.VALUABLE__RIGHT_VALUE:
        return rightValue != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (operator: ");
    result.append(operator);
    result.append(')');
    return result.toString();
  }

} //ValuableImpl
