/**
 * generated by Xtext 2.21.0
 */
package org.xtext.selfie.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.selfie.SelfiePackage;
import org.xtext.selfie.VariableRef;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variable Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VariableRefImpl extends ValuableImpl implements VariableRef
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VariableRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SelfiePackage.Literals.VARIABLE_REF;
  }

} //VariableRefImpl
