/*
 * generated by Xtext 2.21.0
 */
package org.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSelfieScopeProvider extends DelegatingScopeProvider {
}
