/**
 * generated by Xtext 2.21.0
 */
package org.xtext.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.selfie.Model;
import org.xtext.tests.SelfieInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(SelfieInjectorProvider.class)
@SuppressWarnings("all")
public class SelfieParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("def pi: 3.1415;");
      _builder.newLine();
      _builder.append("def r: 5;");
      _builder.newLine();
      _builder.append("def umfang: 2 * pi * r;");
      _builder.newLine();
      _builder.append("def pi2 : 3.1415926;");
      _builder.newLine();
      _builder.append("def nearlySame : 2 * pi2 * r - umfang;");
      _builder.newLine();
      _builder.append("def s : 10;");
      _builder.newLine();
      _builder.append("s := s + (s / 2);\t\t\t");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
