/**
 * generated by Xtext 2.21.0
 */
package org.xtext.selfie;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calculation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.selfie.SelfiePackage#getCalculation()
 * @model
 * @generated
 */
public interface Calculation extends Valuable
{
} // Calculation
