/**
 * generated by Xtext 2.21.0
 */
package org.xtext.selfie;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.selfie.SelfiePackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends Expression
{
} // Declaration
