/**
 * generated by Xtext 2.21.0
 */
package org.xtext.selfie;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Valuable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selfie.Valuable#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.selfie.Valuable#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.selfie.Valuable#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.selfie.SelfiePackage#getValuable()
 * @model
 * @generated
 */
public interface Valuable extends Declaration, Assignment
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Valuable)
   * @see org.xtext.selfie.SelfiePackage#getValuable_Left()
   * @model containment="true"
   * @generated
   */
  Valuable getLeft();

  /**
   * Sets the value of the '{@link org.xtext.selfie.Valuable#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Valuable value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.selfie.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.xtext.selfie.Operator
   * @see #setOperator(Operator)
   * @see org.xtext.selfie.SelfiePackage#getValuable_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link org.xtext.selfie.Valuable#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.xtext.selfie.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Valuable)
   * @see org.xtext.selfie.SelfiePackage#getValuable_Right()
   * @model containment="true"
   * @generated
   */
  Valuable getRight();

  /**
   * Sets the value of the '{@link org.xtext.selfie.Valuable#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Valuable value);

} // Valuable
